[package]
name = "enclave-check"
version = "0.1.0"
authors = ["Reuven Podmazo <reuven@enigma.co>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]

[build-dependencies]
cbindgen = "0.13"
